name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Restore client-side libraries
      run: |
        dotnet tool install -g microsoft.web.librarymanager.cli
        libman restore
      working-directory: IdentityApp
    - name: Build
      run: dotnet build --no-restore --configuration release
