name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run:  |
        dotnet restore IdentityApp\IdentityApp.sln
        dotnet restore ExampleApp\ExampleApp.sln
    - name: Restore client-side libraries
      run: |
        dotnet tool install -g microsoft.web.librarymanager.cli
        libman restore
      working-directory: IdentityApp
    - name: Build projects
      run: |
        dotnet build --no-restore --configuration Release --verbosity normal IdentityApp\IdentityApp.sln
        dotnet build --no-restore --configuration Release --verbosity normal ExampleApp\ExampleApp.sln
    - name: Publish projects
      run: |
        dotnet publish --no-build --configuration Release --verbosity normal IdentityApp\IdentityApp.sln
        dotnet publish --no-build --configuration Release --verbosity normal ExampleApp\ExampleApp.sln
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: AspNetCoreIdentityBook
        path: | 
          IdentityApp\Release\net5.0\publish
          ExampleApp\Release\net5.0\publish
